permalink: /:year/:month/:day/:title.html
markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 尹亚坤
  email: yinyakun123@126.com
  link: http://github.com/lanacon
  weibo: http://weibo.com/lanacon
  github: http://github.com/lanacon

# 站点信息
title: 尹亚坤的博客 
description: 尹亚坤的博客
url: http://github.com/lanacon
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://ww1.sinaimg.cn/large/7f5ba233gw1exmmqayproj20u00k00wr.jpg
favicon: http://ww1.sinaimg.cn/large/7f5ba233gw1exmmqayproj20u00k00wr.jpg

# google analytics 设置

# disqus 设置
disqus:
shortname: yinyakun-zh

excerpt_separator: "\n\n"

safe:        false
watch:       false    # deprecated
server:      false    # deprecated
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true
