permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 尹亚坤
  email: yinyakun123@126.com
  link: http://github.com/lanacon
  weibo: http://weibo.com/lanacon
  github: http://github.com/lanacon

# 站点信息
title: 尹亚坤的博客 
description: 尹亚坤的博客
url: http://github.com/lanacon
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: suyan-zh
