permalink: /:year/:month/:day/:title.html
markdown: markdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 尹亚坤
  email: yinyakun123@126.com
  link: http://github.com/lanacon
  weibo: http://weibo.com/lanacon
  github: http://github.com/lanacon

# 站点信息
title: 尹亚坤的博客 
description: 尹亚坤的博客
url: http://github.com/lanacon
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://ww1.sinaimg.cn/large/7f5ba233gw1exmmqayproj20u00k00wr.jpg
favicon: http://ww1.sinaimg.cn/large/7f5ba233gw1exmmqayproj20u00k00wr.jpg

# google analytics 设置

# disqus 设置
disqus:
shortname: yinyakun-zh

host: 127.0.0.1
port: 4000
